/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as OauthSessionEndedRouteImport } from './routes/oauth/session-ended'
import { Route as GuestVerifyOtpRouteImport } from './routes/_guest/verify-otp'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestSigninRouteImport } from './routes/_guest/signin'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestCheckEmailRouteImport } from './routes/_guest/check-email'
import { Route as AuthenticatedConsoleRouteRouteImport } from './routes/_authenticated/console/route'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console/index'
import { Route as AuthenticatedOauthConsentRouteImport } from './routes/_authenticated/oauth/consent'
import { Route as AuthenticatedConsoleThemeRouteImport } from './routes/_authenticated/console/theme'
import { Route as AuthenticatedConsoleSiteRouteImport } from './routes/_authenticated/console/site'
import { Route as AuthenticatedConsoleIntegrationRouteImport } from './routes/_authenticated/console/integration'
import { Route as AuthenticatedConsoleAuthRouteImport } from './routes/_authenticated/console/auth'

const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthSessionEndedRoute = OauthSessionEndedRouteImport.update({
  id: '/oauth/session-ended',
  path: '/oauth/session-ended',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestVerifyOtpRoute = GuestVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSigninRoute = GuestSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestCheckEmailRoute = GuestCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthenticatedConsoleRouteRoute =
  AuthenticatedConsoleRouteRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)
const AuthenticatedOauthConsentRoute =
  AuthenticatedOauthConsentRouteImport.update({
    id: '/oauth/consent',
    path: '/oauth/consent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleThemeRoute =
  AuthenticatedConsoleThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)
const AuthenticatedConsoleSiteRoute =
  AuthenticatedConsoleSiteRouteImport.update({
    id: '/site',
    path: '/site',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)
const AuthenticatedConsoleIntegrationRoute =
  AuthenticatedConsoleIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)
const AuthenticatedConsoleAuthRoute =
  AuthenticatedConsoleAuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => AuthenticatedConsoleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/callback': typeof CallbackRoute
  '/signout': typeof SignoutRoute
  '/console': typeof AuthenticatedConsoleRouteRouteWithChildren
  '/check-email': typeof GuestCheckEmailRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/signin': typeof GuestSigninRoute
  '/signup': typeof GuestSignupRoute
  '/verify-otp': typeof GuestVerifyOtpRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
  '/': typeof AuthenticatedIndexRoute
  '/console/auth': typeof AuthenticatedConsoleAuthRoute
  '/console/integration': typeof AuthenticatedConsoleIntegrationRoute
  '/console/site': typeof AuthenticatedConsoleSiteRoute
  '/console/theme': typeof AuthenticatedConsoleThemeRoute
  '/oauth/consent': typeof AuthenticatedOauthConsentRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/signout': typeof SignoutRoute
  '/check-email': typeof GuestCheckEmailRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/signin': typeof GuestSigninRoute
  '/signup': typeof GuestSignupRoute
  '/verify-otp': typeof GuestVerifyOtpRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
  '/': typeof AuthenticatedIndexRoute
  '/console/auth': typeof AuthenticatedConsoleAuthRoute
  '/console/integration': typeof AuthenticatedConsoleIntegrationRoute
  '/console/site': typeof AuthenticatedConsoleSiteRoute
  '/console/theme': typeof AuthenticatedConsoleThemeRoute
  '/oauth/consent': typeof AuthenticatedOauthConsentRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signout': typeof SignoutRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteRouteWithChildren
  '/_guest/check-email': typeof GuestCheckEmailRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/signin': typeof GuestSigninRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_guest/verify-otp': typeof GuestVerifyOtpRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/console/auth': typeof AuthenticatedConsoleAuthRoute
  '/_authenticated/console/integration': typeof AuthenticatedConsoleIntegrationRoute
  '/_authenticated/console/site': typeof AuthenticatedConsoleSiteRoute
  '/_authenticated/console/theme': typeof AuthenticatedConsoleThemeRoute
  '/_authenticated/oauth/consent': typeof AuthenticatedOauthConsentRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/callback'
    | '/signout'
    | '/console'
    | '/check-email'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/verify-otp'
    | '/oauth/session-ended'
    | '/'
    | '/console/auth'
    | '/console/integration'
    | '/console/site'
    | '/console/theme'
    | '/oauth/consent'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/signout'
    | '/check-email'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/verify-otp'
    | '/oauth/session-ended'
    | '/'
    | '/console/auth'
    | '/console/integration'
    | '/console/site'
    | '/console/theme'
    | '/oauth/consent'
    | '/console'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_guest'
    | '/callback'
    | '/signout'
    | '/_authenticated/console'
    | '/_guest/check-email'
    | '/_guest/forgot-password'
    | '/_guest/signin'
    | '/_guest/signup'
    | '/_guest/verify-otp'
    | '/oauth/session-ended'
    | '/_authenticated/'
    | '/_authenticated/console/auth'
    | '/_authenticated/console/integration'
    | '/_authenticated/console/site'
    | '/_authenticated/console/theme'
    | '/_authenticated/oauth/consent'
    | '/_authenticated/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  SignoutRoute: typeof SignoutRoute
  OauthSessionEndedRoute: typeof OauthSessionEndedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/session-ended': {
      id: '/oauth/session-ended'
      path: '/oauth/session-ended'
      fullPath: '/oauth/session-ended'
      preLoaderRoute: typeof OauthSessionEndedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/verify-otp': {
      id: '/_guest/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof GuestVerifyOtpRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signin': {
      id: '/_guest/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof GuestSigninRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/check-email': {
      id: '/_guest/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof GuestCheckEmailRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
    '/_authenticated/oauth/consent': {
      id: '/_authenticated/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof AuthenticatedOauthConsentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/theme': {
      id: '/_authenticated/console/theme'
      path: '/theme'
      fullPath: '/console/theme'
      preLoaderRoute: typeof AuthenticatedConsoleThemeRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
    '/_authenticated/console/site': {
      id: '/_authenticated/console/site'
      path: '/site'
      fullPath: '/console/site'
      preLoaderRoute: typeof AuthenticatedConsoleSiteRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
    '/_authenticated/console/integration': {
      id: '/_authenticated/console/integration'
      path: '/integration'
      fullPath: '/console/integration'
      preLoaderRoute: typeof AuthenticatedConsoleIntegrationRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
    '/_authenticated/console/auth': {
      id: '/_authenticated/console/auth'
      path: '/auth'
      fullPath: '/console/auth'
      preLoaderRoute: typeof AuthenticatedConsoleAuthRouteImport
      parentRoute: typeof AuthenticatedConsoleRouteRoute
    }
  }
}

interface AuthenticatedConsoleRouteRouteChildren {
  AuthenticatedConsoleAuthRoute: typeof AuthenticatedConsoleAuthRoute
  AuthenticatedConsoleIntegrationRoute: typeof AuthenticatedConsoleIntegrationRoute
  AuthenticatedConsoleSiteRoute: typeof AuthenticatedConsoleSiteRoute
  AuthenticatedConsoleThemeRoute: typeof AuthenticatedConsoleThemeRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
}

const AuthenticatedConsoleRouteRouteChildren: AuthenticatedConsoleRouteRouteChildren =
  {
    AuthenticatedConsoleAuthRoute: AuthenticatedConsoleAuthRoute,
    AuthenticatedConsoleIntegrationRoute: AuthenticatedConsoleIntegrationRoute,
    AuthenticatedConsoleSiteRoute: AuthenticatedConsoleSiteRoute,
    AuthenticatedConsoleThemeRoute: AuthenticatedConsoleThemeRoute,
    AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
  }

const AuthenticatedConsoleRouteRouteWithChildren =
  AuthenticatedConsoleRouteRoute._addFileChildren(
    AuthenticatedConsoleRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRouteRoute: typeof AuthenticatedConsoleRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOauthConsentRoute: typeof AuthenticatedOauthConsentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRouteRoute: AuthenticatedConsoleRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOauthConsentRoute: AuthenticatedOauthConsentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GuestRouteRouteChildren {
  GuestCheckEmailRoute: typeof GuestCheckEmailRoute
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestSigninRoute: typeof GuestSigninRoute
  GuestSignupRoute: typeof GuestSignupRoute
  GuestVerifyOtpRoute: typeof GuestVerifyOtpRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestCheckEmailRoute: GuestCheckEmailRoute,
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestSigninRoute: GuestSigninRoute,
  GuestSignupRoute: GuestSignupRoute,
  GuestVerifyOtpRoute: GuestVerifyOtpRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  SignoutRoute: SignoutRoute,
  OauthSessionEndedRoute: OauthSessionEndedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
