/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as OauthSessionEndedRouteImport } from './routes/oauth/session-ended'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ConsoleThemeRouteImport } from './routes/console/theme'
import { Route as ConsoleSiteRouteImport } from './routes/console/site'
import { Route as ConsoleIntegrationRouteImport } from './routes/console/integration'
import { Route as ConsoleBrandingRouteImport } from './routes/console/branding'
import { Route as ConsoleAuthRouteImport } from './routes/console/auth'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const OauthSessionEndedRoute = OauthSessionEndedRouteImport.update({
  id: '/oauth/session-ended',
  path: '/oauth/session-ended',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleThemeRoute = ConsoleThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSiteRoute = ConsoleSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleIntegrationRoute = ConsoleIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleBrandingRoute = ConsoleBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAuthRoute = ConsoleAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/console/auth': typeof ConsoleAuthRoute
  '/console/branding': typeof ConsoleBrandingRoute
  '/console/integration': typeof ConsoleIntegrationRoute
  '/console/site': typeof ConsoleSiteRoute
  '/console/theme': typeof ConsoleThemeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/console/auth': typeof ConsoleAuthRoute
  '/console/branding': typeof ConsoleBrandingRoute
  '/console/integration': typeof ConsoleIntegrationRoute
  '/console/site': typeof ConsoleSiteRoute
  '/console/theme': typeof ConsoleThemeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
  '/console': typeof ConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/signin': typeof SigninRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/console/auth': typeof ConsoleAuthRoute
  '/console/branding': typeof ConsoleBrandingRoute
  '/console/integration': typeof ConsoleIntegrationRoute
  '/console/site': typeof ConsoleSiteRoute
  '/console/theme': typeof ConsoleThemeRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/session-ended': typeof OauthSessionEndedRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/callback'
    | '/signin'
    | '/verify-otp'
    | '/console/auth'
    | '/console/branding'
    | '/console/integration'
    | '/console/site'
    | '/console/theme'
    | '/oauth/consent'
    | '/oauth/session-ended'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/signin'
    | '/verify-otp'
    | '/console/auth'
    | '/console/branding'
    | '/console/integration'
    | '/console/site'
    | '/console/theme'
    | '/oauth/consent'
    | '/oauth/session-ended'
    | '/console'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/callback'
    | '/signin'
    | '/verify-otp'
    | '/console/auth'
    | '/console/branding'
    | '/console/integration'
    | '/console/site'
    | '/console/theme'
    | '/oauth/consent'
    | '/oauth/session-ended'
    | '/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  SigninRoute: typeof SigninRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthSessionEndedRoute: typeof OauthSessionEndedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/oauth/session-ended': {
      id: '/oauth/session-ended'
      path: '/oauth/session-ended'
      fullPath: '/oauth/session-ended'
      preLoaderRoute: typeof OauthSessionEndedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/theme': {
      id: '/console/theme'
      path: '/theme'
      fullPath: '/console/theme'
      preLoaderRoute: typeof ConsoleThemeRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/site': {
      id: '/console/site'
      path: '/site'
      fullPath: '/console/site'
      preLoaderRoute: typeof ConsoleSiteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/integration': {
      id: '/console/integration'
      path: '/integration'
      fullPath: '/console/integration'
      preLoaderRoute: typeof ConsoleIntegrationRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/branding': {
      id: '/console/branding'
      path: '/branding'
      fullPath: '/console/branding'
      preLoaderRoute: typeof ConsoleBrandingRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/auth': {
      id: '/console/auth'
      path: '/auth'
      fullPath: '/console/auth'
      preLoaderRoute: typeof ConsoleAuthRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleAuthRoute: typeof ConsoleAuthRoute
  ConsoleBrandingRoute: typeof ConsoleBrandingRoute
  ConsoleIntegrationRoute: typeof ConsoleIntegrationRoute
  ConsoleSiteRoute: typeof ConsoleSiteRoute
  ConsoleThemeRoute: typeof ConsoleThemeRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleAuthRoute: ConsoleAuthRoute,
  ConsoleBrandingRoute: ConsoleBrandingRoute,
  ConsoleIntegrationRoute: ConsoleIntegrationRoute,
  ConsoleSiteRoute: ConsoleSiteRoute,
  ConsoleThemeRoute: ConsoleThemeRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  SigninRoute: SigninRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthSessionEndedRoute: OauthSessionEndedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
